### ISSUE TITLE
set_conf MO_GIT_URL reports both error and success

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#12]
root@VM-16-2-debian:~# mo_ctl set_conf MO_GIT_URL=https://github.com/matrixorigin/matrixone.git
/data/mo_ctl/conf/env.sh: line 77: https://github.com/matrixorigin/matrixone.git=: No such file or directory
2023-07-06_20:21:04    [INFO]    Setting conf: MO_GIT_URL=https://github.com/matrixorigin/matrixone.git
2023-07-06_20:21:04    [INFO]    Key is already set in conf file before, updating it now
2023-07-06_20:21:04    [INFO]    Succeeded

**Comment by aronchanisme** [comment]
Reason: this is because a wrong conf is set
```bash
mo_ctl set_conf https://github.com/matrixorigin/matrixone.git
```

in conf file:
<img width="551" alt="企业微信截图_28b80dd2-db89-41de-9212-0074568fdc82" src="https://github.com/matrixorigin/mo_ctl_standalone/assets/46433151/ff096615-acab-4470-818b-7f78da431ed4">

it's fixed now, with restrictions on setting confs as below, and any invalid conf will be skipped. 
1) key must in default `conf/env.sh`, otherwise will be considered as invalid
2) value must not be empty
3) conf must follow the format `key1=value1,key2=value2,...,keyN=valueN` or `key=value`

**Comment by dengn** [comment]
fixed.
