### ISSUE TITLE
[Question]: 偶发错误

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#39]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id: e.g. v0.1.0 or 8b23a93
- OS type: e.g. MacOS 13/Debian 11
- Other info: e.g. 2c cpu, 4g mem, 250g hdd

### Issue Description

root@VM-16-14-debian:~/mo2/matrixone# mo_ctl connect
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
chdir: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory

### Steps to Reproduce

MO_PATH是/root/mo2，然后我在/root/mo2/matrixone目录下。有的时候不管执行啥mo_ctl命令都会出这个错。

**Comment by aronchanisme** [comment]
mo_ctl uses command `getwcd`, and if you're running mo_ctl command on a path that no longer exists, you will get such an error like this, this may be due to path removed by `mo_ctl uninstall` 
```bash
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
```
It's a normal behavior on a Unix-like system, thus you only need to change your directory to another one which still exists, and re-execute mo_ctl command again, then the error will go away
![企业微信截图_16892490364677](https://github.com/matrixorigin/mo_ctl_standalone/assets/46433151/79b5d41f-7ab2-4400-887b-42015ca1ad30)
![企业微信截图_16892490516922](https://github.com/matrixorigin/mo_ctl_standalone/assets/46433151/64d77eb4-a474-486a-9ce0-dcc6069e5204)
This url might be helpful.
https://blog.csdn.net/whatday/article/details/103869176/

**Comment by aronchanisme** [comment]
mo_ctl will exit now if you execute it on a directory that does not exist 
![image](https://github.com/matrixorigin/mo_ctl_standalone/assets/46433151/a9c2eb8a-8ef7-4b1a-9b90-c2029a61a670)
