### ISSUE TITLE
[Bug]: 1.1.0和1.1.1版本的mo二进制路径已变化，无法按以前的配置

### ISSUE THREAD

**Issue by dengn** [matrixorigin/mo_ctl_standalone#59]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Environment

- Version or commit-id: e.g. v0.1.0 or 8b23a93
- OS type: e.g. MacOS 13/Debian 11
- Other info: e.g. 2c cpu, 4g mem, 250g hdd

### Issue Description

https://github.com/matrixorigin/matrixorigin.io.cn/issues/975

### Steps to Reproduce

https://github.com/matrixorigin/matrixorigin.io.cn/issues/975

**Comment by aronchanisme** [comment]
To be optimized:

Will need to judge conf `MO_DEPLOY_MODE=xxx` to decide MO's data path
avaialbe values: `git` | `binary` | `docker`

When,
1. `MO_DEPLOY_MODE=git`: if `MO_PATH=/data/mo/`, mo_ctl will try to `git clone` source code of matrixone.git into `/data/mo/matrixone/`
2. `MO_DEPLOY_DEME=binary`: if `MO_PATH=/data/mo/`, mo_ctl will try to locate `mo-service` under path `/data/mo/`
3. `MO_DEPLOY_DEME=docker`: `MO_PATH` is ignored since `MO_CONTAINER_DATA_HOST_PATH` will be used as data path of mo container on deploed host

**Comment by aronchanisme** [comment]
done
